    <div class='arrow'>
        <a href='_url_parent_list_'>
            <!--* _CREATED_FUNDAMENTAL_NAME_ *-->
        </a>        
    </div>
    <div class='arrow'>
        <a href='_url_parent_list_'>
            <!--* _CREATED_PARENT_NAME_ *-->
        </a>        
    </div>
    <div class='arrow'>
        <a>
            <!--* _PARENT_SPEC_NAME_ *-->
        </a>
    </div>
	<div class='arrow'>
		<a href='(url child1 list)'>
		    <!--* _CREATED_MODULE_NAME_ *-->
		</a>	    
	</div>
<div class='arrow'><?= (!empty($content['galleryParent_title'])) ? $content['galleryParent_title']:'' ?></div>
<div class='arrow'>Edycja galerii</div> 