<?php   
    $content = $this -> get('content');
?>

<!--
    Start form
-->
<form enctype="multipart/form-data" action="/cms-strona-glowna-zapisz" method="post" id="form">   

<!--
    Define is it edit or adding new page
-->   
<?php
    if(!empty($content['inputs']['id']))
    {
?>
       <input type="hidden" name="id" id="id" value="<?= $content['inputs']['id'] ?>" /> 
<?php
    }
?>

<!--
    Images path
-->
<div class="contenerForPath">
	<div class="arrow">
		<a href="/cms-strona-glowna">
		    <?= $lang['Homepage']?>
		</a>	    
	</div> 
	<div class="arrow">
<?php
    if(!empty($content['inputs']['id']))
    {
?>
       <?= $lang['Edition']?> 
<?php
    }
    else 
    {       
?>	    
    <?= $lang['New page']?> 
<?php
    }    
?>       	       
	</div>		
			
</div>


<!--
    Buttons -> Save and Back and Gallery
-->
<div class="upper-buttons">
    <a href="<?= $_SERVER['HTTP_REFERER'] ?>" class="first-button"><button class="add_button" type="button"><?= $lang['Back']?></button></a>
    <button class="add_button second-button" type="submit"><?= $lang['Save']?></button> 
    
<?php
    if(!empty($content['inputs']['id']))
    {
?>
    <a href="/cms-strony-edytuj-<?= $content['inputs']['id'] ?>-galeria" class="third-button"><button class="add_button" type="button"><?= $lang['Go to the gallery']?></button></a>  
<?php
    }
    else 
    {       
?>      
    <button class="add_button third-button" type="submit"><?= $lang['Save']?></button>   
<?php
    }    
?>         
</div>

<!--
    Errors
-->

<?php
    if(!empty($content['errors']))
    {
?>
        <div class="show-errors">
<?php
        foreach($content['errors'] as $error)
        {
?>
            <a class="show-errors-a"><?= $error ?></a>
<?php            
        }
?>
        </div>  
<?php             
    }
?>

<!--
    Pass - success with adding 
--> 
<?php
    if(!empty($_SESSION['pass']))
    {
?>
        <div class="show-pass">
            <a class="show-errors-a"><?= $_SESSION['pass'] ?></a>
        </div>  
<?php  
         unset($_SESSION['pass']);  
    }
?>
   
    
<!--
    Name of page
-->   
<div class="name-of-page"> 
    <h1>
<?php
    if(!empty($content['inputs']['id']))
    {
?>
       <?= $lang['Page editing']?> 
<?php
    }
    else 
    {       
?>      
    <?= $lang['New page']?> 
<?php
    }    
?>   
    </h1>
</div> 

<!--------------------------------------------------------------
    Title of box
-->   
<div class="one-block-title">
    <h2><?= $lang['Main elements']?></h2>
</div>

<!--
    TITLE
    Box - input 580px 
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Title']?>:
    </div>
    <div class="one-block-input">
        <input type="text"  name="title" id="title" class="input580 count-it" maxlength="300" value="<?= (!empty($content['inputs']['title'])) ? $content['inputs']['title']:'' ?>" />
    </div>    
</div>


<!--
    CONTENT
    Box - textarea
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Content']?>:
    </div>
    <div class="one-block-input">
        <textarea style="width:500px; height: 100px;" id="editor1" name="content"><?= (!empty($content['inputs']['content'])) ? $content['inputs']['content']:'' ?></textarea>
    </div>    
</div>




<script>
//froala
$(function() {
    var type = 'homepage';
    $('#editor1').froalaEditor({
         height: 300,
         width: 700,
        //image upload
        imageUploadURL: '/cms-strona-glowna-dodaj-obraz',
        imageUploadMethod: 'POST',
        imageUploadParams: {type: type},
        //images load
        imageManagerLoadURL: "/cms-strony-pokaz-obraz",
        imageManagerLoadParams: {type: type},
        imageManagerLoadMethod: "POST",
        //image delete
        imageManagerDeleteURL: '/cms-strony-usun-obraz',
        imageManagerDeleteParams: {type: type},
        //language
        language: '<?=$_SESSION['cms_lang']?>'
        
        })
      });   
</script>

<!--
    GALLERY
    Box - select
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Gallery']?>:
    </div>
    <div class="one-block-input">
        <select name="show_gallery" class="select100">
            <option value="0" <?= ($content['inputs']['gallery'] === '0') ? 'selected':'' ?> >Brak</option>
            <option value="1" <?= ($content['inputs']['gallery'] === '1') ? 'selected':'' ?> >Tak</option>
        </select>
    </div> 
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_gallery']?>
        </div>
    </div> 
    <!-- Question Mark End -->          
</div>

<!---------------------------------------------------------------------------
    Title of box
-->   
<div class="one-block-title">
    <h2><?= $lang['Image']?></h2>
</div>    

<?php
    if($content['inputs']['temp_image'] === 1)
    {
?>
<!--
    TEMPORARY IMAGE
    Box - select
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Current image']?>:
    </div>
    <div class="one-block-input">
        <img src="<?= $content['inputs']['temp_image_path'] ?>" />
    </div>          
</div>  
<!--
    Path to the image
-->  
<input type="hidden" name="temp_image_path" id="temp_image_path" value="<?= $content['inputs']['temp_image_path'] ?>" />
<input type="hidden" name="temp_image" id="temp_image" value="<?= $content['inputs']['temp_image'] ?>" />

<?php
    }
    elseif(!empty($content['inputs']['img']) || !empty($content['inputs']['current_img']))
    {
?>
<!--
    CURRENT SAVED IMAGE    Box - select
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Current image']?>:
    </div>
    <div class="one-block-input">
        <img src="<?= (!empty($content['inputs']['img'])) ?  $content['inputs']['img']:$content['inputs']['current_img']   ?>" />
    </div>          
</div>  
<!--
    Path to the image
-->  
<input type="hidden" name="current_img" id="current_img" value="<?= $content['inputs']['img'] ?>" />
<?php
    }
?>
    
<!--
    IMAGE
    Box - select
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
<?php
    if($content['inputs']['temp_image'] === 1 || !empty($content['inputs']['img']))
    {
?> 
        <?= $lang['Change image']?>:
<?php
    }
    else 
    {
?>
        <?= $lang['Add image']?>:
<?php
    }
?>                  
    </div>
    <div class="one-block-input">
        <input type="file"  name="image" id="image" />
    </div> 
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_image']?>
        </div>
    </div> 
    <!-- Question Mark End -->          
</div>    
    
<!--
    IMAGE ALT
    Box - input 580px 
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Image description']?>:
    </div>
    <div class="one-block-input">
        <input type="text"  name="image_alt" id="image_alt" class="input580 count-it" maxlength="300"  value="<?= (!empty($content['inputs']['image_alt'])) ? $content['inputs']['image_alt']:'' ?>" />
    </div>  
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_image_alt']?>
        </div>
    </div> 
    <!-- Question Mark End -->           
</div>    

<!--
    IMAGE TITLE
    Box - input 580px 
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Image title']?>:
    </div>
    <div class="one-block-input">
        <input type="text"  name="image_title" id="image_title" class="input580 count-it" maxlength="300" value="<?= (!empty($content['inputs']['image_title'])) ? $content['inputs']['image_title']:'' ?>" />
    </div> 
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_image_title']?>
        </div>
    </div> 
    <!-- Question Mark End -->          
</div>  

<!--
    FILE NAME
    Box - input 580px 
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['File name']?>:
    </div>
    <div class="one-block-input">
        <input type="text"  name="image_file_name" id="image_file_name" class="input580 count-it" maxlength="300" value="<?= (!empty($content['inputs']['image_file_name'])) ? $content['inputs']['image_file_name']:'' ?>" />
    </div> 
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_image_file_name']?>
        </div>
    </div> 
    <!-- Question Mark End -->          
</div>  
    
<!------------------------------------------------------------------------------
    Title of box
-->   
<div class="one-block-title">
    <h2><?= $lang['Meta tags']?></h2>
</div>     
    
<!--
    META TITLE
    Box - input 580px 
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Title']?>:
    </div>
    <div class="one-block-input">
        <input type="text"  name="meta_title" id="meta_title" class="input580 count-it" maxlength="300" value="<?= (!empty($content['inputs']['meta_title'])) ? $content['inputs']['meta_title']:'' ?>" />
    </div> 
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_meta_title']?>
        </div>
    </div> 
    <!-- Question Mark End -->          
</div>    
    
<!--
    DESCRIPTION
    Box - input 580px 
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Description']?>:
    </div>
    <div class="one-block-input">
        <input type="text"  name="meta_description" id="meta_description" class="input580 count-it" maxlength="300" value="<?= (!empty($content['inputs']['meta_description'])) ? $content['inputs']['meta_description']:'' ?>" />
    </div> 
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_meta_description']?>
        </div>
    </div> 
    <!-- Question Mark End -->          
</div>     
    
<!--
    KEYWORDS
    Box - input 580px 
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Keywords']?>:
    </div>
    <div class="one-block-input">
        <input type="text"  name="meta_keywords" id="meta_keywords" class="input580 count-it" maxlength="300"  value="<?= (!empty($content['inputs']['meta_keywords'])) ? $content['inputs']['meta_keywords']:'' ?>" />
    </div> 
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_meta_keywords']?>
        </div>
    </div> 
    <!-- Question Mark End -->          
</div>      
    
<!--
    AUTHOR
    Box - input 580px 
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Author']?>:
    </div>
    <div class="one-block-input">
        <input type="text"  name="meta_author" id="meta_author" class="input580 count-it" maxlength="300"  value="<?= (!empty($content['inputs']['meta_author'])) ? $content['inputs']['meta_author']:'' ?>" />
    </div> 
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_meta_author']?>
        </div>
    </div> 
    <!-- Question Mark End -->          
</div>       
    
<!--
    ROBOTS
    Box - select
-->  
<div class="one-block clearfixer">
    <div class="one-block-name">
        <?= $lang['Robots']?>:
    </div>
    <div class="one-block-input">
        <select name="meta_robots" class="select200">
            <option value="index, follow" <?= ($content['inputs']['meta_robots'] === 'index, follow') ? 'selected':'' ?> >index, follow</option>
            <option value="index, nofollow" <?= ($content['inputs']['meta_robots'] === 'index, nofollow') ? 'selected':'' ?> >index, nofollow</option>
            <option value="noindex, nofollow" <?= ($content['inputs']['meta_robots'] === 'noindex, nofollow') ? 'selected':'' ?> >noindex, nofollow</option>
            <option value="noindex, follow" <?= ($content['inputs']['meta_robots'] === 'noindex, follow') ? 'selected':'' ?> >noindex, follow</option>
        </select>
    </div> 
    <!-- Question Mark -->
    <div class="div_mark" id="div_header_mark">
        <img src="public/images/cms/question_mark.png" />
        <div class="div_note" id="div_header_note">
            <?= $lang['mark_meta_robots']?>
        </div>
    </div> 
    <!-- Question Mark End -->          
</div>       
    
    
<!--
    BUTTONS
-->     
<div class="downer-buttons">  
    <a href="<?= $_SERVER['HTTP_REFERER'] ?>" class="first-button"><button class="add_button" type="button"><?= $lang['Back']?></button></a>
    <button class="add_button second-button" type="submit"><?= $lang['Save']?></button> 
    <button class="add_button third-button" type="submit"><?= $lang['Save']?></button>  
</div>  <!-- main_content_content_second_buttons -->  


					

</form>	




<script src="js/cms/cms_scripts.js"></script>

