		<style>
			#main_content_content_second_one p a{color:#03a9ff; text-decoration: none;}
		</style>
<!--
    Images path
-->
<div class='contenerForPath'>
    <div class='arrow'>
        <a href='/cms/_CREATED_URL_'>
            Newsite CMS - Strona Główna
        </a>        
    </div>  
</div>

<div id="main_content_content">
	<div id="main_content_content_firt">
		<h1>Newsite CMS<a href=""></a></h1>
	</div>
	<div id="main_content_content_second">
		<div id="main_content_content_second_one">
			<p>To jest główna strona <b>CMS - Systemu Zarządzania Treścią </b>Twojej strony internetowej.</p>
			<p>Aby edytować elementy strony www skorzystaj z menu po lewej stronie.</p>
			<!--<p>Jeśli chcesz uzyskać pomoc wejdź<a href=""> tutaj </a>lub skontaktuj się z <a href="mailto:adres e-mail"> działem pomocy.</a></p><br /><br />-->
			<p><b>Samouczek</b></p>
			<p>Na stronie znajdują się czerwone znaki zapytania: <img src="/public/images/cms/question_mark.png">. Po kliknięciu na znak zapytania pojawi się krótka notka z informacją o funkcjonalności danego elementu.</p>
			<p>Znaki zapytania można znaleźć na różnych podstronach CMS'a.</p>
		</div>
	</div>
</div>
<script src='/js/cms/cms_scripts.js'></script>	