<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script> 
	</head>
	<body>
		<style>
		.define-table {width:30px; }
		.create-new-table {display: inline-block; cursor: pointer; }
		.div-table {margin-top: 1px; }
			.table-input {width: 100px; border: 1px solid #e9e9e9; margin-right: 1px; }
			.table-delete-column {width: 100px; display: inline-block; }
			.table-deleter {color: #b00000; font-size:75%; cursor: pointer; }
			.table-deleter:hover {color: red; }
			.table-adder {color: #0000b7;; cursor: pointer; }
			.table-adder:hover {color: blue;}
		</style>
		
		
		Stwórz tabele: <input type="" class='define-table' id="new-table-rows-amount" /> x <input type="" class='define-table' id="new-table-columns-amount" /><a id="create-new-table" class="table-adder create-new-table">Stwórz</a><br />
		<a>Usuń tabelę</a><br />
		<a id="table-add-row" class="table-adder">Dodaj wiersz</a> <a id="table-add-column" class="table-adder">Dodaj kolumnę</a><br />
		Tabela <a class='table-current-rows-amount'>2</a>x<a class='table-current-columns-amount'>3</a>:
		<form method='post' action="tablephp.php">
			<input type="hidden" name="firstTableCmsContent" value="">
			<input type="hidden" name="firstTableColumnsAmount" value="">
			<input type='submit' />
		
		<div id='whole-table'></div>
		</form>
		<script>
			$( document ).ready(function() {
			    $('[name="firstTableCmsContent"]').val($('#whole-table').html());
			    $('[name="firstTableColumnsAmount"]').val($('.table-input').length / $('.table-row').length);
			});
			// Update input fot php table 
			$(document).on('input', '.firstTable', function(){
			    $('[name="firstTableCmsContent"]').val($('#whole-table').html());
			});
			// Create new table
			$('#create-new-table').click(function(){
				if ($('#whole-table').html().trim() !== '') {
					var r = confirm("Obecna tabela zostanie usunięta!\nCzy na pewno chcesz stworzyć nową tabelę?");
					if (r == true) {
					} else {
					    return;
					}
				}
				$('#whole-table').empty();
				var rowsAmount = $('#new-table-rows-amount').val();
				var columnsAmount = $('#new-table-columns-amount').val();
				if (isNaN(parseInt(rowsAmount)) || isNaN(parseInt(columnsAmount))) {
					alert('Wpisz ilość kolumn i wierszy nowej tabeli.');
					return;
				}
				// Create columns for append every row
				var allColumns = [];
				var allColumnsDeleter = [];
				for (var i=0; i<columnsAmount; i++) {
					allColumns.push('<input type="text" class="table-input firstTable" name="firstTable[]" value="" />');
					allColumnsDeleter.push('<a class="table-delete-column table-deleter">Usuń kolumnę</a>');
				}
				allColumns = allColumns.join('');
				allColumns = allColumns + '<a class="table-delete-row table-deleter">Usuń wiersz</a>';
				allColumnsDeleter = allColumnsDeleter.join('');
				// Create rows
				for (var i=0; i<rowsAmount; i++) {
					$('#whole-table').append('<div class="table-row div-table">' + allColumns + '</div>');
				}
				$('#whole-table').append('<div class="div-table div-table-column-deleter">' + allColumnsDeleter + '</div>');
				rowsAndColumnsUpdater();
			});
			// Main row adder
			$('#table-add-row').click(function(){
				var allColumns = [];
				for (var i=0; i<$('.table-input').length / $('.table-row').length; i++) {
					allColumns.push('<input type="text" class="table-input firstTable" name="firstTable[]" value="" />');
				}
				allColumns = allColumns.join('');
				$('.div-table-column-deleter').before('<div class="table-row div-table">' + allColumns + '<a class="table-delete-row table-deleter">Usuń wiersz</a></div>');
				rowsAndColumnsUpdater();
			});
			// Main column adder
			$('#table-add-column').click(function(){
				$('.table-row .table-delete-row').before('<input type="text" class="table-input firstTable" name="firstTable[]" value="" />');
				$('.div-table-column-deleter').append('<a class="table-delete-column table-deleter">Usuń kolumnę</a>');
				rowsAndColumnsUpdater();
			});
			// Delete existed table
			function removeExistedTable() {
				$('#whole-table').empty();
				$('.table-current-rows-amount').html('0');
				$('.table-current-columns-amount').html('0');
			}
			// Rows and columns counter
			function rowsAndColumnsUpdater() {
				var showRowsAmount = $('.table-current-rows-amount');
				var showColumnsAmount = $('.table-current-columns-amount');
				if ($('.table-row').length === 0 || $('.table-input').length === 0) {
					removeExistedTable();
				} else {
					console.log($('.table-row').length);
					$('.table-current-rows-amount').html($('.table-row').length);
					$('.table-current-columns-amount').html($('.table-input').length / $('.table-row').length);
					$('[name="firstTableCmsContent"]').val($('#whole-table').html());
					$('[name="firstTableColumnsAmount"]').val($('.table-input').length / $('.table-row').length);
				}
			}
			
			// Delete row
			$(document).on('click', '.table-delete-row', function(){
				$(this).parent().remove();
				rowsAndColumnsUpdater();
			});
			// Delete column
			$(document).on('click', '.table-delete-column', function(){
				var index = $(this).index();
				$('.div-table').each(function(){
					$(this).children().eq(index).remove();
					rowsAndColumnsUpdater();
				});
			});

			
		</script>
		<!--
						<div class="table-row div-table">
				<input type='text' class="table-input" name='firstTable[]' />
				<input type='text' class="table-input" name='' />
				<input type='text' class="table-input" name='' />
				<a class='table-delete-row table-deleter'>Usuń wiersz</a>
			</div>
			<div class="table-row div-table">
				<input type="text" class="table-input" name="" />
				<input type='text' class="table-input" name='' />
				<input type='text' class="table-input" name='' />
				<a class='table-delete-row table-deleter'>Usuń wiersz</a>
			</div>
			<div class="div-table div-table-column-deleter">
				<a class='table-delete-column table-deleter'>Usuń kolumnę</a>
				<a class='table-delete-column table-deleter'>Usuń kolumnę</a>
				<a class='table-delete-column table-deleter'>Usuń kolumnę</a>
			</div>
		-->
	</body>
</html>