		   <div class="one_gallery_thumb_child1">     
		        <p>
		            <a class="left">Thumb ' + thumb_number + ' szerokość</a>
		            <a class="right"><input type="text" name="gal_thumb_width_child1[]" class="gal_thumb_width_child1" /></a>
		        </p> 
		        <p>
		            <a class="left">Thumb ' + thumb_number + ' wysokość</a>
		            <a class="right"><input type="text" name="gal_thumb_height_child1[]" class="gal_thumb_height_child1" /></a>
		        </p> 	
		   </div>