		<div class="one-images_child1 grey-element">

			<h4>Zdjęcie <span class="number">' + count_good + '</span></h4>
	        <p>
	            <a class="left">Nazwa w CMSie</a>
	            <a class="right"><input type="text" name="image_name_child1[]" class="image_name_child1" /></a>
	        </p> 		
	        <p>
	            <a class="left">Max wielkość (kilobajty)</a>
	            <a class="right"><input type="text" name="image_maxkb_child1[]" class="image_maxkb_child1" /></a>
	        </p> 	
	        <p>
	            <a class="left">Max szerokość</a>
	            <a class="right"><input type="text" name="image_maxwidth_child1[]" class="image_maxwidth_child1" /></a>
	        </p> 	
	        <p>
	            <a class="left">Max wysokość</a>
	            <a class="right"><input type="text" name="image_maxheight_child1[]" class="image_maxheight_child1" /></a>
	        </p> 		        
	        <p>
	            <a class="left">Żądana szerokość</a>
	            <a class="right"><input type="text" name="image_reqwidth_child1[]" class="image_reqwidth_child1" /></a>
	        </p> 		        
	        <p>
	            <a class="left">Żądana wysokość</a>
	            <a class="right"><input type="text" name="image_reqheight_child1[]" class="image_reqheight_child1" /></a>
	        </p> 
	        <div class="thumbs_child1">

	        </div>
	        <div class="add_thumb_child1 adder-style">Dodaj miniaturkę</div>	 	        
	        <a class="delete_one_own_child1 deleter">Usuń</a> 	
		</div>