		<div class="one-own-column_child1 grey-element">
			<h4>Kolumna ' + count_good + '</h4>
	        <p>
	            <a class="left">Nazwa w Mysql</a>
	            <a class="right"><input type="text" id="own_mysql_name_child1[]" name="own_mysql_name_child1[]" class="own_mysql_name_child1" /></a>
	        </p> 	
	        <p>
	            <a class="left">Typ</a>
	            <a class="right"><select name="own_type_child1[]" class="own_type_child1"><option value="varchar">varchar</option><option value="int">int</option><option value="text">text</option></select></a>
	        </p>         
	        <p>
	            <a class="left">Długość</a>
	            <a class="right"><input type="text" id="own_length_child1[]" name="own_length_child1[]" class="own_length_child1" /></a>
	        </p>         
	        <p>
	            <a class="left">Nazwa z CMS</a>
	            <a class="right"><input type="text" id="own_cms_name_child1[]" name="own_cms_name_child1[]" class="own_cms_name_child1" /></a>
	        </p>              			
			<a class="delete_one_own_child1">Usuń</a>
		</div>