		        <p>
		            <a class="left">Thumb ' + thumb_number + ' szerokość</a>
		            <a class="right"><input type="text" name="image' + number + '_thumbwidth_child1[]" class="image' + number + '_thumbwidth thumb_child1" /></a>
		        </p> 
		        <p>
		            <a class="left">Thumb ' + thumb_number + ' wysokość</a>
		            <a class="right"><input type="text" name="image' + number + '_thumbheight_child1[]" class="image' + number + '_thumbheight_child1" /></a>
		        </p> 	