<?php

require($_SERVER['DOCUMENT_ROOT']."/creator/lib/lead/lead.php");


	$images = array('add', 'add');
	$widths = array('1920', '1500');
	$heights = array('1080', '1200');
	$name = 'Articles';
	$prefix = 'articles';
	
	$router = new cms_config_createImageModule($images, $widths, $heights, $name, $prefix);
	echo $router->deleteExistedConfig();
	
	$existedConfig = file_get_contents($_SERVER['DOCUMENT_ROOT'].'/config/configuration.php');
	$new = $router->startComment($name) . $router->getImagesConfiguration() . $router->endComment($name);
	$newConfig = str_replace('/* Adder */', $new, $existedConfig);
	
	$newConfig = $router->deleteEnters($newConfig);
	
	//$newConfig = preg_replace("/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/", "\n", $newConfig);
	file_put_contents($_SERVER['DOCUMENT_ROOT'].'/config/configuration.php', $newConfig);
	echo "CMS Config zapisany - ".$name."<br />";