
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" xml:lang="en">
	<head>
		<title>Panel - <?= preg_replace('/^www\./','',$_SERVER['HTTP_HOST']);   ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<script type="text/javascript" src="/js/jquery.js"></script>
		
		<link rel="stylesheet" type="text/css" href="public/stylesheets/panel.css"  />
	</head>
	<body>
		<div class="longer longer_up">
				<?php 
				if(!empty($_SESSION['user_panel_avatar']))
				{
				?>
					<div class="avatarus">
						<a href="/panel-account">
							<img src="public/images/panel/avatars/<?=$_SESSION['user_panel_avatar']?>" />
						</a>
					</div>
				
				<? } ?>			
			
			
		</div>
		<div class="longer2 longer_up">
			<a class="goback" href="/"><span class="arrow_up"></span>Powrót na stronę <span><?= $_SERVER['SERVER_NAME'] ?></span></a>
			
			
			<div class="options">
				<?php
				if(!empty($_SESSION['user_panel_login']))
				{
				?>
				Zalogowany 
				<a href="/panel-account" class="user"><?= $_SESSION['user_panel_login']?></a>
				<a href="/panel-logout" class="logout">Wyloguj</a>
				
				<? } ?>
			</div>
		</div>		
		
		<?php $fill = $this -> content; (!empty($fill))? include $fill:'' ?>

	</body>
	
	
</html>