
<section id="panel" class="panel">
    
    <div class="loginer">
        <h2 class="panelh2">Zmień e-mail</h2>
        <h3 class="h3-login"><?= $_SESSION['user_panel_login'] ?></h3>
        <div class="acc-avatar">
            <img src="/public/images/panel/avatars/<?= $_SESSION['user_panel_avatar'] ?>" style="border-radius: 50%;  " />
        </div>
        
<?php
    include('parts/panel_menu.phtml');
?>        

     <form action="/panel-account-update-mail-put" method="POST">
         
        <label class="login-label">
            Nowy e-mail
            <input class="input_input" type="email" maxlength="128" value="<?=  (!empty($content['name']) ? $content['name']:'') ?>" name="new_mail1">
        </label>         

        <label class="login-label">
            Powtórz e-mail
            <input class="input_input" type="email" maxlength="128" value="<?=  (!empty($content['name']) ? $content['name']:'') ?>" name="new_mail2">
        </label>          
        <div class="middle width230"> 
            <button type="submit" class="login-submit margin-top15">Zapisz</button>                    
        </div>         
        
    </form>
  
    
</div>
</section>