<section id="panel" class="panel">
    
    <div class="loginer">
    
       <h1>Reset hasła</h1>	
	   
	   <div class="panel-info-pass">Jeśli istnieje konto zarejestrowane na podany przez Ciebie adres e-mail, otrzymasz nowe hasło.</div>
	   
        <label class="login-label">

            Adres e-mail 
            <input class="input_input" type="text" maxlength="128" value="" name="">
            
        </label>	
        
        
        
        <div class="middle width230"> 
            <button class="login-submit">Zresetuj hasło</button> 
            
            <hr />    
            
            <div class="register-button margin-top15">
                <a class="" href="/panel">Zaloguj się</a>
            </div>             
            
            <div class="register-button margin-top15 margin-left10">
                <a class="" href="/panel-registration">Rejestracja</a>
            </div>            
        </div>
           
	   
	
    </div>
    
</section> 	
	
	
