<!--
    _INPUT_NAME_
    Box - input 580px 
-->  
<div class='one-block clearfixer'>
    <div class='one-block-name'>
        _INPUT_NAME_
    </div>
    <div class='one-block-input'>
        <input type='text'  name='_COLUMN_NAME_' id='_COLUMN_NAME_' class='input580 count-it'  value='<?= (!empty($content['inputs']['_COLUMN_NAME_'])) ? $content['inputs']['_COLUMN_NAME_']:'' ?>' />
    </div>    
</div>