    <div class='arrow'>
        <a href='_parent_list_'>
            <!--* _CREATED_FUNDAMENTAL_NAME_ *-->
        </a>        
    </div>
    <div class='arrow'>
        <a href='_parent_list_'>
            <!--* _CREATED_PARENT_NAME_ *-->
        </a>        
    </div>
    <div class='arrow'>
        <a href='<!--* _URL_ADD_BASIC_ *-->'>
            <?= $content['parent_title'] ?>
        </a>        
    </div>
    <div class='arrow'>
        <a href='<!--* _URL_ADD_CHILD1_BASIC_ *-->'>
            <!--* _CREATED_MODULE_NAME_ *-->
        </a>        
    </div>
    
    