<style>
	.err{font-family: times, Times New Roman, times-roman, georgia, serif;
		font-size: 28px;
		line-height: 40px;
		letter-spacing: -1px;
		color: #444;
		display:block;
		}
</style>
<p>
<a class="err" style="font-size:350%;">404</a>
<a class="err">Strona nie istnieje</a>
</p>
<p>
	Przykro nam, ale strona została przeniesiona lub nigdy nie istniała. <br />
	Sprawdź czy wpisany adres URL jest poprawny.
</p>
<p>
	<a href="/" class="err" style="font-size:150%;">Powrót na stronę główną</a>
</p>
<?php
//var_dump(http_response_code());
?>