		   <div class="one_gallery_thumb">     
		        <p>
		            <a class="left">Thumb ' + thumb_number + ' szerokość</a>
		            <a class="right"><input type="text" name="gal_thumb_width[]" class="gal_thumb_width" /></a>
		        </p> 
		        <p>
		            <a class="left">Thumb ' + thumb_number + ' wysokość</a>
		            <a class="right"><input type="text" name="gal_thumb_height[]" class="gal_thumb_height" /></a>
		        </p> 	
		   </div>