		<div class="one-images grey-element">

			<h4>Zdjęcie <span class="number">' + count_good + '</span></h4>
	        <p>
	            <a class="left">Nazwa w CMSie</a>
	            <a class="right"><input type="text" name="image_name[]" class="image_name" /></a>
	        </p> 		
	        <p>
	            <a class="left">Max wielkość (kilobajty)</a>
	            <a class="right"><input type="text" name="image_maxkb[]" class="image_maxkb" /></a>
	        </p> 	
	        <p>
	            <a class="left">Max szerokość</a>
	            <a class="right"><input type="text" name="image_maxwidth[]" class="image_maxwidth" /></a>
	        </p> 	
	        <p>
	            <a class="left">Max wysokość</a>
	            <a class="right"><input type="text" name="image_maxheight[]" class="image_maxheight" /></a>
	        </p> 		        
	        <p>
	            <a class="left">Żądana szerokość</a>
	            <a class="right"><input type="text" name="image_reqwidth[]" class="image_reqwidth" /></a>
	        </p> 		        
	        <p>
	            <a class="left">Żądana wysokość</a>
	            <a class="right"><input type="text" name="image_reqheight[]" class="image_reqheight" /></a>
	        </p> 
	        <div class="thumbs">

	        </div>
	        <div class="add_thumb adder-style">Dodaj miniaturkę</div>	 	        
	        <a class="delete_one_own deleter">Usuń</a> 	
		</div>