		<div class="one-own-column grey-element">
			<h4>Kolumna ' + count_good + '</h4>
	        <p>
	            <a class="left">Nazwa w Mysql</a>
	            <a class="right"><input type="text" id="own_mysql_name[]" name="own_mysql_name[]" class="own_mysql_name" /></a>
	        </p> 	
	        <p>
	            <a class="left">Typ</a>
	            <a class="right"><select name="own_type[]" class="own_type"><option value="varchar">varchar</option><option value="int">int</option><option value="text">text</option></select></a>
	        </p>         
	        <p>
	            <a class="left">Długość</a>
	            <a class="right"><input type="text" id="own_length[]" name="own_length[]" class="own_length" /></a>
	        </p>         
	        <p>
	            <a class="left">Nazwa z CMS</a>
	            <a class="right"><input type="text" id="own_cms_name[]" name="own_cms_name[]" class="own_cms_name" /></a>
	        </p>              			
			<a class="delete_one_own">Usuń</a>
		</div>