		        <p>
		            <a class="left">Thumb ' + thumb_number + ' szerokość</a>
		            <a class="right"><input type="text" name="image' + number + '_thumbwidth[]" class="image' + number + '_thumbwidth thumb" /></a>
		        </p> 
		        <p>
		            <a class="left">Thumb ' + thumb_number + ' wysokość</a>
		            <a class="right"><input type="text" name="image' + number + '_thumbheight[]" class="image' + number + '_thumbheight" /></a>
		        </p> 	