<?php
    $content = $this -> get('content');   
?>
<!--
    Images path
-->
<div class='contenerForPath'>	
<!--* _TYPE2_PART1 *-->
<!--* _TYPE3_PARENT_PART1 *-->
<!--* _TYPE3_CHILD1_PART1 *-->
</div>
<!--
    Buttons -> Add new site
-->
<div class='upper-buttons'>
	 <a href='<!--* _URL_LIST_ADD_ *-->' class='first-button'><button class='add_button' type='button'><!--* _CREATED_MODULE_ADD_ *--></button></a>                 
</div>
<!--
    Pass - success with adding 
--> 
<?php
    if (!empty( $_SESSION['pass'])) {
?>
        <div class='show-pass'>
            <a class='show-errors-a'><?= $_SESSION['pass'] ?></a>
        </div>  
<?php  
         unset( $_SESSION['pass'] );  
    }
?>
<div style='display: none;' class='show-queue'>
	<a>Kolejność zmieniona</a>
</div>
<!--------------------------------------------------------------
    Name of page
-->   
<div class='name-of-page'> 
    <h1>
    	<!--* _CREATED_MODULE_NAME_ *-->
    </h1>
</div> 

<div class='div-list'>
    
<?php
if(empty($content['list'])) {
?>
    <a class='lackof-com'>Brak.</a>
<?
    
} else {
?>
    <div id='sortable'> 
<?php       
$x = 1;
    foreach ($content['list'] as $element) {
?>  
    <div id='idek-<?= $element['id']  ?>' class='div-list-one-element pagination-one-list clearfixer'>
        <div class='dloe-no'>
            <a><?= $x ?></a>
        </div>
        <div class='dloe-delete'>
            <a class='confirm' href='<!--* _URL_DELETE_ *-->'><?= $lang['Delete']?></a>
        </div> 
        <div class='dloe-name'>
            <?= $element['title']  ?>
        </div>
<!--* _GALLERY_PART1_ *-->
        <div class='dloe-edit'>
            <a href='<!--* _URL_EDIT_ *-->'><?= $lang['Edition']?></a>
        </div>
<!--* _TYPE3_PARENT_PART3 *-->
    </div><!-- div-list-one-element --> 
<?php
    $x++;
    }
}
?>  
</div>    
<?php
    $amountOfButtons = ceil((count($content['list'])/15));
    if ($amountOfButtons > 1) {
?>
<div class='pagination-buttons'>
<?php
		for ($a=1; $a<=$amountOfButtons; $a++) {          
?>
			<span><?= $a ?></span>
<?php
    	}
?>
</div>
<?php
    }
?>
<script>
$('.confirm').click(function(){
	return confirm('Na pewno?');
});
$('#show-all').click(function(){
    $('.div-list-one-element').show();
    $('.pagination-buttons').hide();
});    
$(function() {
	$('#sortable').sortable( {
		placeholder: 'placeholder',
        update: function (event, ui) {
        var elements =  $('#sortable .dloe-no').length;
        for (var x = 0; x <= elements; x++) {
        	$('#sortable .dloe-no:eq( '+ x +' )').text(x+1);
        }
        var data = $(this).sortable('serialize');
        $.ajax({
			data: data,
            type: 'POST',
            url: '<!--* _URL_QUEUE_ *-->',
            success : function(data) {
				$('.show-queue').slideDown('fast');
                setInterval(function(){ $('.show-queue').slideUp('fast'); }, 3000);
            }
        });
        }
	});  
    $( '#sortable' ).disableSelection();
});
</script>
<script src='/js/cms/cms_scripts.js'></script>